os:
  - linux
dist: xenial
services:
  - docker
language: python
python: 3.7.2

#----------------------------------------------------------------------
# Install all tools and check configuration
#----------------------------------------------------------------------
before_install:
  - python --version

#----------------------------------------------------------------------
# Install dependencies
#----------------------------------------------------------------------
install:
  - pip install pyyaml

#----------------------------------------------------------------------
# Launch tests
#----------------------------------------------------------------------
script:
  - python integration_tests.py
