K8sSetup: Local K8s from Docker Desktop for Mac/Windows
useKubeconfig: true
localApiServerURL: https://localk8s.com:8443
K8sClientCert: c29tZWtleQo=
K8sClientCertKey: c29tZWNlcnRrZXkK
K8sClientCertFile: ../xl-infra/__test__/files/test-file
K8sClientCertKeyFile: ../xl-infra/__test__/files/test-file