answers-file: local-kube-kubeconfig-true.yaml
expected-files:
  - cm_answer_file_auto.yaml
expected-xl-values:
  K8sSetup: Local K8s from Docker Desktop for Mac/Windows
  useKubeconfig: true
  localApiServerURL: https://localk8s.com:8443
  K8sClientCert: c29tZWtleQo=
  K8sClientCertKey: c29tZWNlcnRrZXkK