{
 "title": "XebiaLabs Monitoring",
 "description": "A dashboard to help with cost and utilisation",
 "tags": [
  "utilisation",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "${VAR_JOB}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "This dashboard shows requests for CPU, RAM and Storage"
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(\n    count(irate(container_cpu_usage_seconds_total{id=\"/\"}[2m])) by (instance)\n    * on (instance) \n    sum(irate(container_cpu_usage_seconds_total{id=\"/\"}[2m])) by (instance)\n  ) \n  / \n  (sum (kube_node_status_allocatable_cpu_cores))\n) * 100"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(\n    count(container_memory_working_set_bytes{id=\"/\"}) by (instance)\n    * on (instance) \n    sum(avg_over_time(container_memory_working_set_bytes{id=\"/\"}[1m])) by (instance)\n  )\n  /\n  sum(kube_node_status_allocatable_memory_bytes)\n) * 100"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 7, "x": 8, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\"}) / sum(container_fs_limit_bytes{id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Node Utilisation by CPU and RAM requests",
   "type": "table",
   "description": "This table shows the comparison of CPU and RAM requests by applications, vs the capacity of the node",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 2 },
   "targets": [
    {
     "expr": "( \n  sum(kube_pod_container_resource_requests_cpu_cores) by (node) \n  /\n  sum(kube_node_status_allocatable_cpu_cores) by (node)\n) * 100",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "( \n  sum(kube_pod_container_resource_requests_memory_bytes) by (node) \n  /\n  sum(kube_node_status_allocatable_memory_bytes) by (node)\n) * 100",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(container_spec_cpu_shares{namespace!=\"\"})\n  / \n  (sum (kube_node_status_allocatable_cpu_cores) * 1000)\n) * 100"
    }
   ]
  },
  {
   "title": "RAM Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(kube_pod_container_resource_requests_memory_bytes{namespace!=\"\"})\n  /\n  sum(kube_node_status_allocatable_memory_bytes)\n) * 100"
    }
   ]
  },
  {
   "title": "XL Deploy: Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\", app=\"xl-deploy\"}",
     "legendFormat": "JVM current threads [{{kubernetes_pod_name}}]"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\", app=\"xl-deploy\"}",
     "legendFormat": "JVM daemon threads [{{kubernetes_pod_name}}]"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\", app=\"xl-deploy\"}",
     "legendFormat": "JVM deadlocked threads [{{kubernetes_pod_name}}]"
    }
   ]
  },
  {
   "title": "XL Deploy: Java heap memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"$job\", app=\"xl-deploy\"}",
     "legendFormat": "Used [{{kubernetes_pod_name}}]"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"$job\", app=\"xl-deploy\"}",
     "legendFormat": "Max  [{{kubernetes_pod_name}}]"
    }
   ]
  },
  {
   "title": "XL Release: Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\", app=\"xl-release\"}",
     "legendFormat": "JVM current threads [{{kubernetes_pod_name}}]"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\", app=\"xl-release\"}",
     "legendFormat": "JVM daemon threads [{{kubernetes_pod_name}}]"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\", app=\"xl-release\"}",
     "legendFormat": "JVM deadlocked threads [{{kubernetes_pod_name}}]"
    }
   ]
  },
  {
   "title": "XL Release: Java heap memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"$job\", app=\"xl-release\"}",
     "legendFormat": "Used [{{kubernetes_pod_name}}]"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"$job\", app=\"xl-release\"}",
     "legendFormat": "Max  [{{kubernetes_pod_name}}]"
    }
   ]
  }
 ]
}