apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: XL UP
  description: |
    The blueprint deploys XL Deploy, XL Release and XL-k8s-foundation into a existing K8s (local single node K8s, on premises multinode K8s Cluster or and AWS EKS Cluster)
  author: XebiaLabs
  version: 1.0
parameters:
  - name: K8sSetup
    type: Select
    description: "Select the Kubernetes setup where XL Devops Platform will be installed"
    options:
      - Local K8s from Docker for Mac/Windows
      - AWS EKS
      - Plain multinode K8s cluster

  - name: useKubeconfig
    type: Confirm
    description: "Do you want to use K8s current-context from ~/.kube/config?"
    dependsOnTrue: !fn k8s.config().IsAvailable
    default: true
    saveInXlVals: true

  - name: apiServerURL
    type: Input
    description: "Enter the ApiServerURL of your K8s installation:"
    default: !fn k8s.config().ClusterServer
    dependsOnTrue: !expression "!useKubeconfig && K8sSetup != 'Local K8s from Docker for Mac/Windows'"
    saveInXlVals: true

  - name: localApiServerURL
    type: Input
    description: "Enter the ApiServerURL of your K8s installation:"
    value: !fn os._defaultapiserverurl()
    dependsOnTrue: !expression "K8sSetup == 'Local K8s from Docker for Mac/Windows'"
    saveInXlVals: true

  - name: K8sClientCertFile
    type: File
    description: "Enter the path of your K8s Client Certificate:"
    dependsOnTrue: !expression "!useKubeconfig && K8sSetup != 'AWS EKS' "
    saveInXlVals: true
    default: /tmp/k8sClientCert.crt

  - name: K8sClientCertKeyFile
    type: File
    description: "Enter the path of your K8s Client Certificate Key:"
    saveInXlVals: true
    dependsOnTrue: !expression "!useKubeconfig && K8sSetup != 'AWS EKS' "
    default: /tmp/k8sClientCertKey.key

  - name: K8sClientCert
    type: Editor
    description: "Using K8s Client Certificate from your context"
    dependsOnTrue: !expression "useKubeconfig && K8sSetup != 'AWS EKS' "
    saveInXlVals: true
    value: !fn k8s.config().UserClientCertificateData

  - name: K8sClientCertKey
    type: Editor
    description: "Using k8s Client Certificate Key from your context"
    saveInXlVals: true
    dependsOnTrue: !expression "useKubeconfig && K8sSetup != 'AWS EKS' "
    value: !fn k8s.config().UserClientKeyData

  - name: eksClusterName
    type: Input
    description: "What is the AWS EKS cluster name?"
    dependsOnTrue: !expression "!useKubeconfig && K8sSetup == 'AWS EKS' "
    default: !fn k8s.config().ContextCluster
    saveInXlVals: true

  - name: isAwsCfgAvailable
    type: Confirm
    value: !fn aws.credentials().IsAvailable
    dependsOnTrue: !expression "K8sSetup == 'AWS EKS' "

  - name: useAWSconfig
    type: Confirm
    description: "Do you want to use AWS credentials from ~/.aws/credentials file?"
    dependsOnTrue: !expression "isAwsCfgAvailable"
    # if this is set then in case the question is skipped and default value is true, but this is a string not a boolean. if !useAWSconfig  is used will fail because the you cannot use !string. BUG in blueprint feature
    #default: true
    saveInXlVals: true

  - name: AWSAccessKey
    type: Input
    secret: true
    description: "What is the AWS Access Key ID?"
    dependsOnTrue: !expression "!useAWSconfig && K8sSetup == 'AWS EKS' "
    saveInXlVals: true
    default: !fn aws.credentials().AccessKeyID

  - name: AWSAccessSecret
    type: Input
    secret: true
    description: "What is the AWS Secret Access Key?"
    dependsOnTrue: !expression "!useAWSconfig && K8sSetup == 'AWS EKS' "
    saveInXlVals: true
    default: !fn aws.credentials().SecretAccessKey

  - name: InstallXLD
    type: Confirm
    description: "Would you like to install XL Deploy?"
    default: true

  - name: InstallXLR
    type: Confirm
    description: "Would you like to install XL Release?"
    default: true

  - name: xlVersion
    type: Select
    saveInXlVals: true
    description: "Choose version of Xebialabs DevOps Platform:"
    options:
      - 8.5.2
    value: 8.5.2

  - name: dockerRepo
    type: Select
    saveInXlVals: true
    description: "Choose docker repository:"
    options:
      - xebialabs
    value: xebialabs

  - name: xldAdminPass
    type: Input
    secret: true
    saveInXlVals: true
    description: "Enter XL Deploy admin user password you want to use:"
    dependsOnTrue: InstallXLD
    default: !expression "randPassword()"

  - name: xldLic
    type: File
    saveInXlVals: true
    description: "Enter the path of the  XL Deploy License:"
    dependsOnTrue: InstallXLD
    default: /tmp/deployit-license.lic

  - name: xldDbName
    type: Input
    saveInXlVals: true
    description: "Enter your XLD Database name:"
    dependsOnTrue: !expression "InstallXLD"
    default: xl-deploy

  - name: xldDbUser
    type: Input
    saveInXlVals: true
    description: "Enter your XLD Database username:"
    dependsOnTrue: InstallXLD
    default: sa

  - name: xldDbPass
    type: Input
    secret: true
    saveInXlVals: true
    description: "Enter your XLD Database password:"
    dependsOnTrue: InstallXLD
    default: !expression "randPassword()"

  - name: efsId
    type: Input
    saveInXlVals: true
    description: "Enter your AWS EFS ID:"
    dependsOnTrue: !expression "InstallXLD && K8sSetup == 'AWS EKS'"
    default: fs-38d079f0

  - name: efsRegion
    type: Input
    saveInXlVals: true
    description: "Enter your AWS EFS Region:"
    dependsOnTrue: !expression "InstallXLD && K8sSetup == 'AWS EKS'"
    default: eu-west-1

  - name: nsfServerHost
    type: Input
    saveInXlVals: true
    description: "Enter your NFS Server name or ip:"
    dependsOnTrue: !expression "K8sSetup == 'Plain multinode K8s cluster'"
    default: 172.16.0.45

  - name: nsfSharePath
    type: Input
    saveInXlVals: true
    description: "Enter your NFS share path:"
    dependsOnTrue: !expression "K8sSetup == 'Plain multinode K8s cluster'"
    default: /xebialabs-k8s

  - name: xldWorkHostpath
    type: Input
    saveInXlVals: true
    description: "Enter the local directory path that will be used as a work directory for XL Deploy:"
    dependsOnTrue: !expression "K8sSetup == 'Local K8s from Docker for Mac/Windows' && InstallXLD"
    default: /tmp/xld-work

  - name: xlrAdminPass
    type: Input
    secret: true
    saveInXlVals: true
    description: "Enter XL Release admin user password you want to use:"
    dependsOnTrue: InstallXLR
    default: !expression "randPassword()"

  - name: xlrLic
    type: File
    saveInXlVals: true
    description: "Enter the path of  XL Release License:"
    dependsOnTrue: InstallXLR
    default: /tmp/xl-release-license.lic

  - name: xlrDbName
    type: Input
    saveInXlVals: true
    description: "Enter your XLR Database name:"
    dependsOnTrue: !expression "InstallXLR"
    default: xl-release

  - name: xlrDbUser
    type: Input
    saveInXlVals: true
    description: "Enter your XLR Database username:"
    dependsOnTrue: InstallXLR
    default: xl-release

  - name: xlrDbPass
    type: Input
    secret: true
    saveInXlVals: true
    description: "Enter your XLR Database password:"
    dependsOnTrue: InstallXLR
    default: !expression "randPassword()"

  - name: xlrReportDbName
    type: Input
    saveInXlVals: true
    description: "Enter your XLR Report Database name:"
    dependsOnTrue: !expression "InstallXLR"
    default: xl-release-report

  - name: xlrReportDbUser
    type: Input
    saveInXlVals: true
    description: "Enter your XLR Report Database username:"
    dependsOnTrue: InstallXLR
    default: xl-release-report

  - name: xlrReportDbPass
    type: Input
    secret: true
    saveInXlVals: true
    description: "Enter your XLR Report Database password:"
    dependsOnTrue: InstallXLR
    default: !expression "randPassword()"

  - name: xlrRepositoryHostpath
    type: Input
    saveInXlVals: true
    description: "Enter the local directory path where XL Release will store its own repository:"
    dependsOnTrue: !expression "K8sSetup == 'Local K8s from Docker for Mac/Windows' && InstallXLR"
    default: /tmp/xlr-repository

  - name: xlKeyStore
    type: File
    saveInXlVals: true
    description: "Enter the path of your XL KeyStore:"
    default: /tmp/keystore.jceks

  - name: xlKeyStorePass
    type: Input
    secret: true
    saveInXlVals: true
    description: "Enter your XL KeyStore Password"
    default: test123

  - name: InstallMonitoring
    type: Confirm
    description: "Do you want to install Monitoring?"
    default: !expression "K8sSetup != 'Local K8s from Docker for Mac/Windows'"
    dependsOnTrue: !expression "K8sSetup != 'Local K8s from Docker for Mac/Windows'"

  - name: monitoringUser
    type: Input
    saveInXlVals: true
    description: "What is the username for monitoring?"
    default: admin
    dependsOnTrue: InstallMonitoring

  - name: monitoringUserPass
    type: Input
    # Secret can't be use currently due to the bug: https://xebialabs.atlassian.net/browse/LOVE-662
    #secret: true
    saveInXlVals: true
    description: "What is the password for monitoring user?"
    default: !expression "randPassword()"
    dependsOnTrue: InstallMonitoring

  - name: PostgresqlWorkHostpath
    type: Input
    saveInXlVals: true
    description: "Enter the local directory path where  Postgresql will store its data:"
    dependsOnTrue: !expression "K8sSetup == 'Local K8s from Docker for Mac/Windows'"
    default: /tmp/xl-postgresql

  - name: postgresMaxConn
    type: Input
    saveInXlVals: true
    description: "Specify max_connections parameter for PostgreSQL:"
    default: 512
    dependsOnTrue: !expression "K8sSetup != 'Local K8s from Docker for Mac/Windows'"

  - name: postgresSharedBuff
    type: Input
    saveInXlVals: true
    description: "Specify shared_buffers parameter for PostgreSQL:"
    default: 512MB
    dependsOnTrue: !expression "K8sSetup != 'Local K8s from Docker for Mac/Windows'"

  - name: postgresEffectCacheSize
    type: Input
    saveInXlVals: true
    description: "Specify effective_cache_size parameter for PostgreSQL:"
    default: 1GB
    dependsOnTrue: !expression "K8sSetup != 'Local K8s from Docker for Mac/Windows'"

  - name: postgresSyncCommit
    type: Input
    saveInXlVals: true
    description: "Specify synchronous_commit parameter for PostgreSQL:"
    default: "off"
    dependsOnTrue: !expression "K8sSetup != 'Local K8s from Docker for Mac/Windows'"

  - name: postgresMaxWallSize
    type: Input
    saveInXlVals: true
    description: "Specify max_wal_size parameter for PostgreSQL:"
    default: 256MB
    dependsOnTrue: !expression "K8sSetup != 'Local K8s from Docker for Mac/Windows'"

files:
  #xl-k8s-foundation
  - path: xebialabs/xl-k8s-foundation.yaml.tmpl
  - path: kubernetes/xl-k8s-foundation/ha-proxy-ingress-controller/ingress-controller.yaml
  - path: kubernetes/xl-k8s-foundation/ha-proxy-ingress-controller/service-l7.yaml
    dependsOnTrue: !expression "K8sSetup == 'AWS EKS'"
  - path: kubernetes/xl-k8s-foundation/ha-proxy-ingress-controller/default-backend.yaml
  - path: kubernetes/xl-k8s-foundation/xebialabs-service-internal.yaml
  - path: kubernetes/xl-k8s-foundation/aws-gp2-storageclass.yaml
    dependsOnTrue: !expression "K8sSetup != 'Local K8s from Docker for Mac/Windows'"
  - path: kubernetes/xl-k8s-foundation/postgresql/xl-postgresql.yaml.tmpl
  - path: kubernetes/xl-k8s-foundation/nfs-client-provisioner/rbac.yaml
    dependsOnTrue: !expression "K8sSetup != 'Local K8s from Docker for Mac/Windows'"
  - path: kubernetes/xl-k8s-foundation/nfs-client-provisioner/deployment.yaml
    dependsOnTrue: !expression "K8sSetup != 'Local K8s from Docker for Mac/Windows'"
  - path: kubernetes/xl-k8s-foundation/nfs-client-provisioner/storageclass.yaml
    dependsOnTrue: !expression "K8sSetup != 'Local K8s from Docker for Mac/Windows'"
  #xl-deploy
  - path: xebialabs/xl-deploy.yaml.tmpl
    dependsOnTrue: InstallXLD
  - path: kubernetes/xl-deploy/local-db/xld-deployment-single-node.yaml.tmpl
    dependsOnTrue: InstallXLD
  - path: kubernetes/xl-deploy/external-db/hot-standby/aws-efs/aws-efs-storageclass.yaml
    dependsOnTrue: InstallXLD
  - path: kubernetes/xl-deploy/external-db/hot-standby/aws-efs/aws-efs-rbac.yaml
    dependsOnTrue: InstallXLD
  - path: kubernetes/xl-deploy/external-db/hot-standby/aws-efs/aws-efs-deployment.yaml
    dependsOnTrue: InstallXLD
  - path: kubernetes/xl-deploy/external-db/hot-standby/aws-efs/aws-efs-conf.yaml
    dependsOnTrue: InstallXLD
  - path: kubernetes/xl-deploy/external-db/hot-standby/xld-deployment-hot-standby.yaml.tmpl
    dependsOnTrue: InstallXLD
  - path: kubernetes/xl-deploy/external-db/hot-standby/pvc.yaml.tmpl
    dependsOnTrue: InstallXLD
  #xl-release
  - path: xebialabs/xl-release.yaml.tmpl
    dependsOnTrue: InstallXLR
  - path: kubernetes/xl-release/external-db/active-active/xlr-deployment-active.yaml.tmpl
    dependsOnTrue: InstallXLR
  - path: kubernetes/xl-release/local-db/xlr-deployment-single-node.yaml.tmpl
    dependsOnTrue: InstallXLR
  #efk
  - path: kubernetes/efk-stack/elasticsearch-logging.yaml.tmpl
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/efk-stack/fluentd-config.yaml
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/efk-stack/fluentd-esconfig.yaml
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/efk-stack/kibana.yaml.tmpl
  #pg-stack
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/pg-stack/prometheus.yaml
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/pg-stack/grafana.yaml.tmpl
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/pg-stack/grafana-configmap.yaml
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-cluster-role.yaml
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-cluster-role-binding.yaml
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-deployment.yaml
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-role.yaml
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-role-binding.yaml
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-service.yaml
    dependsOnTrue: InstallMonitoring
  - path: kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-service-account.yaml
    dependsOnTrue: InstallMonitoring
  #xebialabs files
  - path: xebialabs.yaml.tmpl
  - path: xebialabs/common.yaml.tmpl
  - path: xebialabs/deployments.yaml.tmpl
