apiVersion: v1
kind: ServiceAccount
metadata:
  name: xebialabs-admin
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: client-system-rb
subjects:
- kind: ServiceAccount
  name: xebialabs-admin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
